### ISSUE TITLE
P2Pool Issue

### ISSUE THREAD

**Issue by WhiteyCookie** [shermand100/PiNodeXMR#113]
P2Pool isn't working at all. It don't even start at first
("./p2pool not found")
My setup is a raspberry pi 4 with 8gb and a 250gb ssd

Tried to build from source again. No success. Tried to update p2pool by ssh -> setup -> node updates (or similar idk). No success

**Comment by RobFre70** [comment]
Same problem here. 
No raspberry though, but that doesn't matter.

**Comment by RobFre70** [comment]
I reinstalled the complete node again.

No change.

Pool still not working. All workers connection refused. 

No change in network though.

When connecting to public node, all is working fine.

Solution please.

**Comment by shermand100** [comment]
> P2Pool isn't working at all. It don't even start at first ("./p2pool not found") My setup is a raspberry pi 4 with 8gb and a 250gb ssd
> 
> Tried to build from source again. No success. Tried to update p2pool by ssh -> setup -> node updates (or similar idk). No success

Ok, so the "update P2Pool" option from the terminal setup menu can be seen as a soft reset. (Each update element there is a complete remove and reinstall of that component) Because you have a /p2pool not found it's likely there was an install error.

The installer isn't that smart to catch all install errors, so it will tell you it's finished updating but if it failed it doesn't know.

Instead I've output all logs of the updater into "debug.log", so if you look in there if p2pool update has failed again, you will see at the bottom a timestamp for when you started the update (To help you find the content you need) and hopefully a reason why it failed. Usually something as simple as a dependency we can reinstall.

**Comment by shermand100** [comment]
> Same problem here. No raspberry though, but that doesn't matter.
> 
> Message is... Connection refused.

Connection refused is a little different to the above.
What settings are you using for your mining software? Assuming it's XMRig you'll need your node IP with port 3333

Are you mining within your local network or trying to connect from outside?

Does this help?

https://github.com/SChernykh/p2pool#gnulinux

**Comment by RobFre70** [comment]
Yes, I use 192.168.0.167:3333 to connect to the p2pool. It used to work fine.
( My Node and my workerrs are not watched by Adguard. It used to block them before )
I did see an error message during install at the end of install. I could not see what it was though because it was too fast.
I reinstalled from the beginning. blockchain is allmost there. Then I will try again.

**Comment by RobFre70** [comment]
I got it all working now as it should be. But there is an other problem.

I can not see progress in p2pool explorer. If I follow the link it tells me that P2POOL is outdated. So I used your update-p2pool.sh from GitHub. It is on 4.x now. But I still can't see progress. Everything else is up to date too.

What could be wrong here?

Rob

**Comment by shermand100** [comment]
As a note, 'support script 3' currently in the setup menu, under 'system settings ' installs the P2Pool pre-compiled binary from the P2Pool GitHub for others that come across this thread.


Anyway, in your case @RobFre70 can you clarify please. If you click on the view P2Pool button on the web UI how far do you get?

?page not found
?just a grey screen
? incorrect data.

**Comment by RobFre70** [comment]
Hi.

I see at all positions N/A.

When I click on FAQ and follow the P2Pool observer I put in my wallet address and there it says I use an outdated version.

Rob

Verzonden met Proton Mail Android

-------- Oorspronkelijk bericht --------
Op 20-09-2024 16:01, schreef shermand100 :

**Comment by RobFre70** [comment]
Update.

For some reason all works fine now. Guess I just had to wait.

Verzonden met Proton Mail Android

-------- Oorspronkelijk bericht --------
Op 20-09-2024 16:01, schreef shermand100 :
